import type { Template } from "arco-cubes-types";

const schema: Template = {
  id: "profile-v2",
  meta_data: {
    name: "profile-v2",
    display_name: "Profile",
    type: "profile",
    description: "",
    tags: [],
    version: "2.0.0",
    created_at: "2025-02-10",
    cover_url:
      "https://public.arco.ai/arco-for-generation/component-covers/profile-v2.png",
  },
  component: "",
  schema: {
    type: "object",
    properties: {
      avatar: {
        type: "string",
        title: "Avatar URL",
        description: "Avatar URL",
        editable: true,
        control: "image",
      },
      name: {
        type: "string",
        title: "User name",
        description: "User name",
        default: "UserName",
        control: "input",
        editable: true,
      },
      bio: {
        type: "string",
        title: "Bio",
        description: "Bio",
        default: "Wisdom is the light of the eyes",
        control: "input",
        editable: true,
      },
      status: {
        type: "string",
        title: "Online status",
        description: "Online status, default is Active Now",
        control: "input",
        editable: true,
      },
      ip: {
        type: "string",
        title: "IP",
        description: "IP",
        control: "input",
        editable: true,
      },
      name_italic: {
        type: "boolean",
        title: "Name Italic",
        description: "Name Italic",
        default: false,
        control: "switch",
        editable: false,
      },
      header_style: {
        type: "string",
        title: "Header Style",
        description: "Header Style",
        control: "select",
        editable: false,
        options: [
          { title: "Classic", value: "classic" },
          { title: "Portrait", value: "portrait" },
          { title: "Banner", value: "banner" },
        ],
      },
      show_border: {
        type: "boolean",
        title: "Show Border",
        description: "Show Border",
        control: "switch",
        editable: false,
      },
      name_color: {
        type: "string",
        title: "Name Color",
        description: "Name Color",
        control: "color",
        editable: false,
      },
    },
    default: {
      avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
      name: "UserName",
      bio: "Profile Classic Intro",
      status: "Active Now",
      ip: "Location",
      header_style: "classic",
      name_italic: false,
    },
    required: [
      "avatar",
      "name",
      "name_italic",
      "header_style",
      "show_border",
      "name_color",
    ],
    object_order: [
      "avatar",
      "name",
      "bio",
      "status",
      "ip",
      "name_italic",
      "header_style",
      "show_border",
      "name_color",
    ],
  },
  layouts: [
    {
      icon_name: "small",
      name: "Classic",
      data: {
        name_italic: false,
        header_style: "classic",
        show_border: false,
        name_color: "",
      },
    },
    {
      icon_name: "medium",
      name: "Portrait",
      data: {
        name_italic: false,
        header_style: "portrait",
        show_border: false,
        name_color: "",
      },
    },
    {
      icon_name: "large",
      name: "Banner",
      data: {
        name_italic: false,
        header_style: "banner",
        show_border: false,
        name_color: "",
      },
    },
  ],
  preset: {
    "profile-v2-classic": {
      meta_data: {
        display_name: "Profile Classic",
        name: "profile-v2-classic",
        type: "profile",
        description:
          "A user profile header component that elegantly showcases the user’s circular avatar at the top, drawing immediate attention to their profile image. Below the avatar, the user’s name is prominently displayed in bold, stylish typography, accompanied by a concise, inspiring bio. The online status indicator and location tag are neatly aligned at the bottom, enclosed within subtly outlined buttons for a clean, modern look. This component is perfect for personal websites, team collaboration tools, and social platforms where highlighting user information and online presence is essential. On mobile devices, the profile component is fixed at the top of the screen for easy access. On desktop devices, the profile component is displayed on the left side for a balanced layout.",
        cover_url:
          "https://public.arco.ai/arco-for-generation/component-covers/profile-classic.png",
        tags: [
          "profile_preset:classic",
          "layout:vertical",
          "alignment:mobile-center,desktop-left",
          "interaction:show",
          "spacing:balanced",
          "special:status_label,IP_label",
        ],
        version: "2.0.0",
        created_at: "2025-02-10",
      },
      layout_name: "Classic",
      data: {
        name: "UserName",
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        bio: "Profile Portrait Intro",
        status: "Active Now",
        ip: "Location",
        name_italic: false,
        header_style: "classic",
        show_border: false,
        name_color: "",
      },
    },
    "profile-v2-portrait": {
      meta_data: {
        display_name: "Profile Portrait",
        name: "profile-v2-portrait",
        type: "profile",
        description:
          "A profile header component that elegantly displays the user’s name, online status, location, and bio. It features a prominent cover image with a soft gradient overlay, enhancing the visual focus on the centered profile portrait, which blends seamlessly with the background. The user’s name is styled boldly for emphasis, with a concise, inspiring bio positioned just below. At the bottom, the status indicator and location tag are neatly aligned, providing clear, accessible information. This component is perfect for personal portfolios, social platforms, and collaboration tools, offering a visually engaging introduction to user profiles. On mobile devices, the profile component is fixed at the top of the screen for easy access. On desktop devices, the profile component is displayed on the left side for a balanced layout.",
        cover_url:
          "https://public.arco.ai/arco-for-generation/component-covers/profile-portrait.png",
        tags: [
          "profile_preset:portrait",
          "layout:vertical",
          "alignment:mobile-center,desktop-left",
          "interaction:show",
          "spacing:large-top,small-inner",
          "special:status_label,IP_label",
        ],
        version: "2.0.0",
        created_at: "2025-02-10",
      },
      layout_name: "Portrait",
      data: {
        name: "UserName",
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        bio: "Profile Portrait Intro",
        status: "Active Now",
        ip: "Location",
        name_italic: false,
        header_style: "portrait",
        show_border: false,
        name_color: "",
      },
    },
    "profile-v2-banner": {
      meta_data: {
        display_name: "Profile Banner",
        name: "profile-v2-banner",
        type: "profile",
        description:
          "A user profile header component that displays a cover image, user name, bio, online status, and location. The cover image sits at the top with rounded corners, followed by the user’s name in bold uppercase text and a short bio beneath it. The online status and location tag are displayed as badge-style buttons with icons for quick reference. Ideal for personal websites, social platforms, and collaboration tools to highlight key user information. On mobile devices, the profile component is fixed at the top of the screen for easy access. On desktop devices, the profile component is displayed on the left side for a balanced layout.",
        cover_url: "",
        tags: [
          "profile_preset:banner",
          "layout:vertical",
          "alignment:mobile-left,desktop-left",
          "interaction:show",
          "spacing:balanced",
          "special:status_label,IP_label",
        ],
        version: "2.0.0",
        created_at: "2025-02-10",
      },
      layout_name: "Banner",
      data: {
        name: "UserName",
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        bio: "Profile Portrait Intro",
        status: "Active Now",
        ip: "Location",
        name_italic: false,
        header_style: "banner",
        show_border: false,
        name_color: "",
      },
    },
  },
};

export default schema;
