import type { Page } from "arco-cubes-types";

export const data: Page = {
  id: "page-1",
  name: "Page 1",
  description: "Page 1",
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
  theme: {
    meta_data: {
      type: "page",
      name: "Urban Night",
      tags: [
        "global-bg-pattern:monochrome",
        "global-bg-color:black",
        "profile_preset:portrait",
        "icon_style:shaped-monochrome",
        "industry_category:Entertainment,Art,Innovation,Technology,Fashion",
        "style:modern,cyberpunk,mysterious",
        "color-scheme:contrast,bold,vibrant",
        "primary-color:vibrant-orange",
        "font-family-primary:avenir",
        "font-family-secondary:kumar-one",
        "corner:sharp",
        "border:none",
        "shadow:none",
        "spacing:very-tight",
      ],
      description:
        "A modern dark theme featuring vibrant orange accents on deep backgrounds. Sharp corners and compact layouts create a bold, contemporary aesthetic perfect for creative and entertainment websites.",
      created_at: "2025-01-21",
      version: "1.0.0",
    },
    page_config: {
      padding: 16,
      gap: 10,
      background: {
        color: "#FF00FF",
      },
    },
    global_css: {
      "--surface": "0 0 0",
      "--on-surface": "255 255 255",
      "--primary": "40 40 40",
      "--on-primary": "255 255 255",
      "--secondary": "",
      "--on-secondary": "255 255 255",
      "--tertiary": "255 255 255",
      "--on-tertiary": "0 0 0",
      "--radius-base": "0.125rem",
      "--card-border": "1px",
      "--font-family-primary":
        "'Anton', ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
      "--font-family-secondary":
        "'Anton', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
      "--radius-sm": "0.0625rem",
      "--radius-default": "0.125rem",
      "--radius-md": "0.1875rem",
      "--radius-lg": "0.25rem",
      "--radius-xl": "0.375rem",
      "--radius-2xl": "0.5rem",
      "--radius-3xl": "0.75rem",
      "--outline": "54 54 54",
      "--outline-variant": "54 54 54",
    },
    extra_rules: [
      {
        id: "call-to-action-list",
        rule_type: "component_id",
        rule_value: "call-to-action-list",
        data: {
          use_card_radius: true,
        },
      },
    ],
  },
  seo: {
    title: "Page 1",
    description: "Page 1",
    keywords: ["Page 1"],
  },

  layout_groups: [
    {
      group_id: "group-1",
      group_name: "profile-social",
      direction: "col",
    },
    {
      group_id: "group-2",
      group_name: "content",
      direction: "col",
    },
  ],
  data: [
    {
      section_id: "profile",
      component_id: "profile-v2",
      preset_id: "profile-v2-classic",
      layout_group_id: "group-1",
      datas: {
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        name: "UserName Profile",
        bio: "Profile Classic Intro",
        status: "123",
        ip: "a s d",
        header_style: "classic",
        show_border: false,
      },
    },
    {
      section_id: "loading",
      component_id: "loading-v2",
      preset_id: "loading-v2-basic",
      layout_group_id: "group-2",
      datas: {
        url: "https://arco.ai",
      },
    },
    // {
    //   section_id: "profile-1",
    //   component_id: "profile-v2",
    //   preset_id: "profile-v2-portrait",
    //   layout_group_id: "group-1",
    //   datas: {},
    // },
    // {
    //   section_id: "profile-2",
    //   component_id: "profile-v2",
    //   preset_id: "profile-v2-banner",
    //   layout_group_id: "group-1",
    //   datas: {},
    // },
    {
      section_id: "title",
      component_id: "title-v2",
      preset_id: "title-v2-basic",
      layout_group_id: "group-2",
      datas: {
        title: "this is a long long long long long long title",
        description:
          " Description Description Description Description Description Description Description Description Description Description Description Description",
        // align: "left",
      },
    },
    {
      section_id: "general-cta",
      component_id: "general-cta-v2",
      preset_id: "general-cta-v2-small",
      layout_group_id: "group-2",
      layout_name: "Small",
      datas: {
        use_card_radius: false,
        cta_style: "small",
        cta_list: [
          {
            avatar:
              "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
            title:
              "General CTA Small General CTA Small General CTA Small General CTA SmallGeneral CTA SmallGeneral CTA SmallGeneral CTA Small",
            image:
              "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
            jump_url: "https://arco.ai",
          },
          {
            avatar:
              "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
            title:
              "General CTA Small General CTA Small General CTA Small General CTA SmallGeneral CTA SmallGeneral CTA SmallGeneral CTA Small",
            image:
              "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
            jump_url: "https://arco.ai",
          },
          {
            avatar:
              "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
            title:
              "General CTA Small General CTA Small General CTA Small General CTA SmallGeneral CTA SmallGeneral CTA SmallGeneral CTA Small",
            image:
              "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
            jump_url: "https://arco.ai",
          },
          {
            avatar:
              "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
            title:
              "General CTA Small General CTA Small General CTA Small General CTA SmallGeneral CTA SmallGeneral CTA SmallGeneral CTA Small",
            image:
              "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
            jump_url: "https://arco.ai",
          },
          {
            avatar:
              "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
            title: "General CTA Small",
            image:
              "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
            jump_url: "https://arco.ai",
          },
        ],
      },
    },
    {
      section_id: "general-cta-1",
      component_id: "general-cta-v2",
      preset_id: "general-cta-v2-grid",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "general-cta-2",
      component_id: "general-cta-v2",
      preset_id: "general-cta-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "general-cta-3",
      component_id: "general-cta-v2",
      preset_id: "general-cta-v2-carousel",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "123123123",
      component_id: "instagram-profile-v2",
      preset_id: "instagram-profile-v2-small",
      layout_group_id: "group-2",
      layout_name: "Small",
      datas: {
        card_type: "small",
        use_card_radius: false,
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        name: "UserName as asd asd as w q zxc  asd",
        bio: "Profile Classic Intro Profile Classic Intro",
        follower_num: 88888888888,
        post_image_list: [
          "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
          "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
          "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
          "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
        ],
        ins_profile_url: "https://arco.ai",
      },
    },
    {
      section_id: "instagram-profile-1",
      component_id: "instagram-profile-v2",
      preset_id: "instagram-profile-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "instagram-profile-2",
      component_id: "instagram-profile-v2",
      preset_id: "instagram-profile-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "youtube-embed-video-player",
      component_id: "youtube-embed-video-player-v2",
      preset_id: "youtube-embed-video-player-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "youtube-embed-video-player-1",
      component_id: "youtube-embed-video-player-v2",
      preset_id: "youtube-embed-video-player-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "tiktok-embed-video-player",
      component_id: "tiktok-embed-video-player-v2",
      preset_id: "tiktok-embed-video-player-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "tiktok-embed-video-player-1",
      component_id: "tiktok-embed-video-player-v2",
      preset_id: "tiktok-embed-video-player-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "local-video-player",
      component_id: "local-video-player-v2",
      preset_id: "local-video-player-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "local-video-player-1",
      component_id: "local-video-player-v2",
      preset_id: "local-video-player-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "spotify-embed",
      component_id: "spotify-embed-v2",
      preset_id: "spotify-embed-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "spotify-embed-1",
      component_id: "spotify-embed-v2",
      preset_id: "spotify-embed-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "suno-profile",
      component_id: "suno-profile-v2",
      preset_id: "suno-profile-v2-list",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "suno-profile-1",
      component_id: "suno-profile-v2",
      preset_id: "suno-profile-v2-grid",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "local-audio-player",
      component_id: "local-audio-player-v2",
      preset_id: "local-audio-player-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "local-audio-player-1",
      component_id: "local-audio-player-v2",
      preset_id: "local-audio-player-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "social-icon-links",
      component_id: "social-icon-v2",
      preset_id: "social-round-color",
      layout_group_id: "group-1",
      datas: {},
    },
    {
      section_id: "social-icon-links-1",
      component_id: "social-icon-v2",
      preset_id: "social-round-monochrome",
      layout_group_id: "group-1",
      datas: {},
    },
    {
      section_id: "social-icon-links-2",
      component_id: "social-icon-v2",
      preset_id: "social-shaped-monochrome",
      layout_group_id: "group-1",
      datas: {},
    },
    {
      section_id: "social-icon-links-3",
      component_id: "social-icon-v2",
      preset_id: "social-shaped-color",
      layout_group_id: "group-1",
      datas: {},
    },
    {
      section_id: "banner",
      component_id: "banner-v2",
      preset_id: "banner-basic",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "countdown",
      component_id: "countdown-v2",
      preset_id: "countdown-basic-v2",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "email",
      component_id: "email-v2",
      preset_id: "email-small",
      layout_group_id: "group-2",
      layout_name: "Small",
      datas: {
        card_type: "small",
        email: "example@exampleaaaaaaaaa aa a aaaaaaaa",
        title: "Contact U asd asd s",
        description:
          "Get in ad asd as as das a as dasds asd s das d touch with us",
      },
    },
    {
      section_id: "email-1",
      component_id: "email-v2",
      preset_id: "email-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "twitter-profile",
      component_id: "twitter-profile-v2",
      preset_id: "twitter-profile-v2-small",
      layout_group_id: "group-2",
      datas: {
        card_type: "small",
        avatar: "https://public.arco.ai/arco-images/cube/cube-avatar-image.png",
        name: "The name of the twitter profile",
        followers_num: 1000,
        post_text: "The text of the post",
        post_image:
          "https://public.arco.ai/arco-images/cube/cube-gallery-image.png",
        twitter_profile_url: "https://x.com/thearco",
      },
    },
    {
      section_id: "twitter-profile-1",
      component_id: "twitter-profile-v2",
      preset_id: "twitter-profile-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "facebook-profile",
      component_id: "facebook-profile-v2",
      preset_id: "facebook-profile-v2-small",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "facebook-profile-1",
      component_id: "facebook-profile-v2",
      preset_id: "facebook-profile-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "youtube-profile",
      component_id: "youtube-profile-v2",
      preset_id: "youtube-profile-v2-small",
      layout_name: "Small",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "youtube-profile-1",
      component_id: "youtube-profile-v2",
      preset_id: "youtube-profile-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "youtube-profile-2",
      component_id: "youtube-profile-v2",
      preset_id: "youtube-profile-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "tiktok-profile",
      component_id: "tiktok-profile-v2",
      preset_id: "tiktok-profile-v2-small",
      layout_group_id: "group-2",
      layout_name: "Small",
      datas: {},
    },
    {
      section_id: "tiktok-profile-1",
      component_id: "tiktok-profile-v2",
      preset_id: "tiktok-profile-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "tiktok-profile-2",
      component_id: "tiktok-profile-v2",
      preset_id: "tiktok-profile-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "suno-track",
      component_id: "suno-track-v2",
      preset_id: "suno-track-v2-medium",
      layout_group_id: "group-2",
      datas: {},
    },
    {
      section_id: "suno-track-1",
      component_id: "suno-track-v2",
      preset_id: "suno-track-v2-large",
      layout_group_id: "group-2",
      datas: {},
    },
  ],
};
